// Penrose tiling (P3, rhombi) — the famous *aperiodic* tiling: fat (72°) and thin (36°) rhombi that
// tile the plane with 5-/10-fold symmetry and never repeat. There's no lattice, so it's generated by
// **deflation** (Robinson-triangle subdivision, Preshing's algorithm): start from a "sun" of 10 acute
// golden triangles, subdivide D times, then merge each mirror pair of triangles back into a rhombus.
// A triangle is half a rhombus split along the rhombus's diagonal; that diagonal is the one edge whose
// length isn't the unit rhombus side, so it's easy to find and merge across. Result is edge-to-edge, so
// the generic stitch() pairs it like any other tiling. Two shape classes: thin-rhombus / thick-rhombus.

import type { RawTile, Tiling, TilingMeta, Vec2 } from '../types'
import { centroid } from '../geometry'
import { makeShapeDef } from '../shapes'
import { stitch } from '../stitch'
import { weldVertices, windCCW } from './util'

const PHI = (1 + Math.sqrt(5)) / 2
const THIN = makeShapeDef('thin-rhombus', 4)
const THICK = makeShapeDef('thick-rhombus', 4)
const AVG_AREA = 0.81 // ≈ area-weighted mean rhombus area (thick:thin count ratio φ:1), for tile-count parity

const META: TilingMeta = {
  id: 'penrose',
  name: 'Penrose (rhombi)',
  vertexConfig: 'aperiodic · fat + thin rhombi',
  chiral: false,
  edgeToEdge: true,
  // Aperiodic — no lattice. A running index keeps each tile's coordinate unique (generation is
  // deterministic, so ids are stable for a given grid size).
  latticeLabels: ['index'],
}

type Tri = { color: 0 | 1; a: Vec2; b: Vec2; c: Vec2 }

function lerp(u: Vec2, v: Vec2, t: number): Vec2 {
  return { x: u.x + (v.x - u.x) * t, y: u.y + (v.y - u.y) * t }
}

// One deflation step (Preshing). Acute (0) → 2 triangles; obtuse (1) → 3.
function subdivide(tris: Tri[]): Tri[] {
  const out: Tri[] = []
  for (const { color, a, b, c } of tris) {
    if (color === 0) {
      const p = lerp(a, b, 1 / PHI)
      out.push({ color: 0, a: c, b: p, c: b })
      out.push({ color: 1, a: p, b: c, c: a })
    } else {
      const q = lerp(b, a, 1 / PHI)
      const r = lerp(b, c, 1 / PHI)
      out.push({ color: 1, a: r, b: c, c: a })
      out.push({ color: 1, a: q, b: r, c: b })
      out.push({ color: 0, a: r, b: q, c: a })
    }
  }
  return out
}

// A "sun" of 10 acute golden triangles, apexes at the origin, legs = `radius`.
function sun(radius: number): Tri[] {
  const tris: Tri[] = []
  for (let i = 0; i < 10; i += 1) {
    let b: Vec2 = { x: radius * Math.cos(((2 * i - 1) * Math.PI) / 10), y: radius * Math.sin(((2 * i - 1) * Math.PI) / 10) }
    let c: Vec2 = { x: radius * Math.cos(((2 * i + 1) * Math.PI) / 10), y: radius * Math.sin(((2 * i + 1) * Math.PI) / 10) }
    if (i % 2 === 0) [b, c] = [c, b]
    tris.push({ color: 0, a: { x: 0, y: 0 }, b, c })
  }
  return tris
}

const dist = (u: Vec2, v: Vec2) => Math.hypot(u.x - v.x, u.y - v.y)
const keyOf = (u: Vec2, v: Vec2) => {
  const a = `${Math.round(u.x / 1e-4)},${Math.round(u.y / 1e-4)}`
  const b = `${Math.round(v.x / 1e-4)},${Math.round(v.y / 1e-4)}`
  return a <= b ? `${a}|${b}` : `${b}|${a}`
}

// The rhombus diagonal edge (the two rhombus SIDES are equal; the diagonal is the odd one out),
// returned as [shared endpoints], plus the apex (the third vertex).
function diagonalEdge(t: Tri): { p: Vec2; q: Vec2; apex: Vec2 } {
  const lab = dist(t.a, t.b)
  const lbc = dist(t.b, t.c)
  const lca = dist(t.c, t.a)
  const tol = 0.05 * Math.max(lab, lbc, lca)
  if (Math.abs(lbc - lca) <= tol) return { p: t.a, q: t.b, apex: t.c } // legs bc,ca equal → diagonal ab
  if (Math.abs(lab - lca) <= tol) return { p: t.b, q: t.c, apex: t.a } // legs ab,ca → diagonal bc
  return { p: t.c, q: t.a, apex: t.b } // legs ab,bc → diagonal ca
}

export function penroseTiling(n: number): Tiling {
  const half = Math.max(2, (n / 2) * Math.sqrt(AVG_AREA))
  // Deflation depth so the patch (radius ≈ φ^D at unit edge) comfortably covers the region.
  const depth = Math.min(10, Math.max(4, Math.ceil(Math.log((half + 2) * 1.6) / Math.log(PHI))))
  let tris = sun(Math.pow(PHI, depth)) // start big so that after D deflations the rhombus edge is 1
  for (let d = 0; d < depth; d += 1) tris = subdivide(tris)

  // Merge mirror pairs across the shared diagonal (the quantized key absorbs deflation float drift;
  // the final rhombi are welded below so stitch pairs their shared sides exactly).
  const groups = new Map<string, Array<{ p: Vec2; q: Vec2; apex: Vec2 }>>()
  for (const t of tris) {
    const d = diagonalEdge(t)
    const k = keyOf(d.p, d.q)
    const g = groups.get(k)
    if (g) g.push(d)
    else groups.set(k, [d])
  }

  const inRegion = (c: Vec2) => c.x >= -half && c.x <= half && c.y >= -half && c.y <= half
  const kept: Array<{ id: string; shape: string; vertices: Vec2[]; index: number }> = []
  let index = 0
  for (const g of groups.values()) {
    if (g.length !== 2) continue // boundary half-rhombus → drop
    const [t1, t2] = g
    const verts = windCCW([t1.p, t1.apex, t1.q, t2.apex])
    const c = centroid(verts)
    if (!inRegion(c)) continue
    // Classify by acute angle at a corner: thin ≈ 36°, thick ≈ 72°.
    const v1 = { x: t1.apex.x - t1.p.x, y: t1.apex.y - t1.p.y }
    const v2 = { x: t2.apex.x - t1.p.x, y: t2.apex.y - t1.p.y }
    const ang = (Math.acos((v1.x * v2.x + v1.y * v2.y) / (Math.hypot(v1.x, v1.y) * Math.hypot(v2.x, v2.y))) * 180) / Math.PI
    const acute = Math.min(ang, 180 - ang)
    const shape = acute < 54 ? 'thin-rhombus' : 'thick-rhombus'
    kept.push({ id: `${shape === 'thin-rhombus' ? 'pt' : 'pk'}:${index}`, shape, vertices: verts, index })
    index += 1
  }

  weldVertices(kept, 1e-6)
  const raws: RawTile[] = kept.map((t) => ({ id: t.id, shape: t.shape, lattice: [t.index], vertices: t.vertices }))
  return stitch(raws, { 'thin-rhombus': THIN, 'thick-rhombus': THICK }, META)
}
